// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5HBmIhOWbX3fLEVI9womkUmbeK9-YOA',
    appId: '1:671219337997:web:ebfaf2fd767242471abe44',
    messagingSenderId: '671219337997',
    projectId: 'money-tracker-e22c0',
    authDomain: 'money-tracker-e22c0.firebaseapp.com',
    storageBucket: 'money-tracker-e22c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDoQbIeIphxftmo9RSXh5FAeSOud6QhU',
    appId: '1:671219337997:android:44ec7894230a08241abe44',
    messagingSenderId: '671219337997',
    projectId: 'money-tracker-e22c0',
    storageBucket: 'money-tracker-e22c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXSGAIp8dgya682ttCondec37O4kS1bo',
    appId: '1:671219337997:ios:02036e587e24c81d1abe44',
    messagingSenderId: '671219337997',
    projectId: 'money-tracker-e22c0',
    storageBucket: 'money-tracker-e22c0.firebasestorage.app',
    iosBundleId: 'com.example.savu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXSGAIp8dgya682ttCondec37O4kS1bo',
    appId: '1:671219337997:ios:02036e587e24c81d1abe44',
    messagingSenderId: '671219337997',
    projectId: 'money-tracker-e22c0',
    storageBucket: 'money-tracker-e22c0.firebasestorage.app',
    iosBundleId: 'com.example.savu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD5HBmIhOWbX3fLEVI9womkUmbeK9-YOA',
    appId: '1:671219337997:web:ef9c837cca02d9ec1abe44',
    messagingSenderId: '671219337997',
    projectId: 'money-tracker-e22c0',
    authDomain: 'money-tracker-e22c0.firebaseapp.com',
    storageBucket: 'money-tracker-e22c0.firebasestorage.app',
  );
}
